/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.googlecode.climb;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int foreground=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int platform_30=0x7f020003;
        public static final int platform_50=0x7f020004;
        public static final int platform_70=0x7f020005;
        public static final int platform_full=0x7f020006;
        public static final int spot=0x7f020007;
        public static final int title=0x7f020008;
        public static final int waterwaves=0x7f020009;
        public static final int woodshield_big=0x7f02000a;
        public static final int woodshield_med=0x7f02000b;
        public static final int woodshield_small=0x7f02000c;
    }
    public static final class id {
        public static final int button_jump=0x7f050011;
        public static final int button_left=0x7f050013;
        public static final int button_right=0x7f050015;
        public static final int game_view=0x7f050000;
        public static final int highscore_1_name=0x7f050001;
        public static final int highscore_1_platform=0x7f050003;
        public static final int highscore_1_score=0x7f050002;
        public static final int highscore_2_name=0x7f050004;
        public static final int highscore_2_platform=0x7f050006;
        public static final int highscore_2_score=0x7f050005;
        public static final int highscore_3_name=0x7f050007;
        public static final int highscore_3_platform=0x7f050009;
        public static final int highscore_3_score=0x7f050008;
        public static final int highscore_4_name=0x7f05000a;
        public static final int highscore_4_platform=0x7f05000c;
        public static final int highscore_4_score=0x7f05000b;
        public static final int highscore_5_name=0x7f05000d;
        public static final int highscore_5_platform=0x7f05000f;
        public static final int highscore_5_score=0x7f05000e;
        public static final int splash_view=0x7f050016;
        public static final int text_assignment_jump=0x7f050010;
        public static final int text_assignment_left=0x7f050012;
        public static final int text_assignment_right=0x7f050014;
    }
    public static final class layout {
        public static final int credits_layout=0x7f030000;
        public static final int game_layout=0x7f030001;
        public static final int highscore_layout=0x7f030002;
        public static final int main_layout=0x7f030003;
        public static final int settings_layout=0x7f030004;
        public static final int splash_layout=0x7f030005;
    }
    public static final class string {
        public static final int app_developer=0x7f040001;
        public static final int app_name=0x7f040000;
        public static final int credits=0x7f040010;
        public static final int highscore_header_name=0x7f04000d;
        public static final int highscore_header_platform=0x7f04000f;
        public static final int highscore_header_score=0x7f04000e;
        public static final int menu_label_close=0x7f040007;
        public static final int menu_label_credits=0x7f040006;
        public static final int menu_label_help=0x7f040005;
        public static final int menu_label_highscore=0x7f040004;
        public static final int menu_label_newgame=0x7f040002;
        public static final int menu_label_settings=0x7f040003;
        public static final int settings_button_label=0x7f040008;
        public static final int settings_button_label_jump=0x7f040009;
        public static final int settings_button_label_left=0x7f04000b;
        public static final int settings_button_label_press=0x7f04000c;
        public static final int settings_button_label_right=0x7f04000a;
    }
}
